### ISSUE TITLE
consider creating an AUR package

### ISSUE THREAD

**Issue by ninrod** [hbekel/xchainkeys#2]
@hbekel, I see that there's no AUR package for your program.

Arch linux users are known for using [bspwm](https://github.com/baskerville/bspwm), and your program fits very well with this particular window manager.

consider writing an AUR package for your program.

**Comment by hbekel** [comment]
I used to maintain the Arch AUR packages when I was still using Arch, but I orphaned my packages when I left Arch since I have no way of maintaining/testing them anymore. If nobody picked them up, they probably got deleted.

**Comment by ninrod** [comment]
I see. Just out of curiosity, what distro are you using now?
