### ISSUE TITLE
how to create an C-SPC chainkey

### ISSUE THREAD

**Issue by ninrod** [hbekel/xchainkeys#3]
Hi, 

I've read the manual, but could not encounter a way to setup this chain:
```sh
C-SPC :enter
C-SPC t :exec st
```

I'd like that Control + Space be a key. Then C-SPC-t would fire up st terminal.

Is there a way to achieve that?

**Comment by hbekel** [comment]
The error message is pretty clear, just like the manual. Read again.

This is an issue tracker, not a support line.

**Comment by ninrod** [comment]
hey @hbekel, I did not mean to bother you. 

Yes, your are right, I found the answer reading the `/usr/include/X11/keysymdef.h` file.
